### PR TITLE
Week2 backend

### PR DESCRIPTION
**Pull request by NatnaelAlemayehu**

### CODE REVIEW

**Comment by arunpandianp** [comment]
This is on top of #1 right? If we change the base of this PR to branch NatiDev? It'll make it easier to review only the newer changes. We can change it back to main after #1 is merged.

I looked at https://github.com/NatnaelAlemayehu/google-sps/compare/NatiDev...week2-backend and the changes look good.

**Comment by NatnaelAlemayehu** [comment]
@arunpandianp  I am having issues with rebasing week2-backend onto NatiDev. What command do I write? what I did was I checked out on to week2-backend and then typed in git rebase NatiDev  and also I tried git rebase --onto NatiDev

**Comment by arunpandianp** [comment]
```
git log

commit 5ac96ef177719fcda414f4c65b9eb9dfa185b308 (HEAD -> week2-backend, origin/week2-backend)
Author: Natnael Alemayehu <natnaelzewdu0@gmail.com>
Date:   Mon Jun 14 20:32:46 2021 +0000

    add servlet code

commit d9b3b6579e17989b147de90379856a53e890427c
Author: Natnael Alemayehu <natnaelzewdu0@gmail.com>
Date:   Fri Jun 11 06:18:27 2021 +0000

    add fetch method in script js file to return hardcoded response

commit 4fe10186f950706974ed612746384e2b3ae6b862
Author: Natnael Alemayehu <natnaelzewdu0@gmail.com>
Date:   Tue Jun 8 10:08:28 2021 +0000

    add name to hello world

commit cc0279fe5ee85f7197d088e6f876f2c218750702 (origin/NatiDev, NatiDev)
Author: Your Name <you@example.com>
Date:   Tue Jun 8 11:43:42 2021 +0200

    change background color and font color

commit de18f16e57d449c9ec1ed46eda065bed7c5bf80f
Author: Your Name <you@example.com>
Date:   Tue Jun 8 11:42:56 2021 +0200

    add hyperlink to projects

commit d37e0c5f93e11ec485a9285b77913b884b913f90
Author: Natnael Alemayehu <natnaelzewdu0@gmail.com>
Date:   Thu Jun 3 10:17:13 2021 +0000

    add project link to html file
```

>> I am having issues with rebasing week2-backend onto NatiDev

week2-backend is already on top of NatiDev.  I think a rebase is not required.

**Comment by NatnaelAlemayehu** [comment]
@arunpandianp so can you approve my pull request so that I can merge with master?

**Review by arunpandianp — APPROVED** [review]

**Comment by arunpandianp** [comment]
done 👍

**Pull request merged**
